spring.application.name=demo

server.port=8086
spring.kafka.bootstrap.servers=localhost:9092

spring.kafka.streams.application-id=ktable-demo-app
spring.kafka.streams.default-key-serde=org.apache.kafka.common.serialization.Serdes$StringSerde
spring.kafka.streams.default-value-serde=org.apache.kafka.common.serialization.Serdes$StringSerde
